DROP TABLE IF EXISTS user;
DROP TABLE IF EXISTS goals;
DROP TABLE IF EXISTS tasks;

CREATE TABLE user (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  username TEXT UNIQUE NOT NULL,
  password TEXT NOT NULL,
  resolution TEXT
);

CREATE TABLE goals (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  author_id INTEGER NOT NULL,
  priority INTEGER,
  created TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  body TEXT NOT NULL,
  complete BOOLEAN DEFAULT false,
  FOREIGN KEY (author_id) REFERENCES user (id)
);

CREATE TABLE tasks (
	id INTEGER PRIMARY KEY AUTOINCREMENT,
  author_id INTEGER NOT NULL,
	priority INTEGER,
	goal_id INTEGER NOT NULL,
	created TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	body TEXT NOT NULL,
	complete BOOLEAN DEFAULT false,
	FOREIGN KEY (goal_id) REFERENCES goal (id)
);